# Generated by Django 4.2.7 on 2023-11-23 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_worldpopulation_netchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldpopulation',
            name='worldPercentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
