# Generated by Django 4.2.7 on 2023-11-23 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldPopulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField()),
                ('pop1980', models.IntegerField()),
                ('pop2000', models.IntegerField()),
                ('pop2010', models.IntegerField()),
                ('pop2022', models.IntegerField()),
                ('pop2023', models.IntegerField()),
                ('pop2030', models.IntegerField()),
                ('pop2050', models.IntegerField()),
                ('country', models.CharField(max_length=255)),
                ('area', models.IntegerField()),
                ('landAreaKm', models.IntegerField()),
                ('cca2', models.CharField(max_length=2)),
                ('cca3', models.CharField(max_length=3)),
                ('netChange', models.IntegerField()),
                ('growthRate', models.FloatField()),
                ('worldPercentage', models.FloatField()),
                ('density', models.FloatField()),
                ('densityMi', models.FloatField()),
                ('rank', models.IntegerField()),
            ],
        ),
    ]
