# Generated by Django 4.2.7 on 2023-11-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_worldpopulation_worldpercentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginlog',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
